#!/usr/bin/python3

## @file generate_bit_map_header.py
#  @brief This file converts a bitmap txt file into a C header
#  @author Nick-Archi

# [TODO] Who knows...maybe turn this into a class if I'm bored

"""
Objective:
Script created to convert a bitmap file into a char bitmap header file. 
Helps speed up edits and ensures that the correct bitmap is generated.
"""

import argparse

# global variable used to store the name of the file
orig_file = ""
parser = None

## @brief Reads in bitmap file to create list of lists for further processing
## @return list of bitmap values 
def create_list(filepath="") -> list:
    ret = []  

    try:
        with open(filepath) as f:
            data = f.read()
    except FileNotFoundError:
        print("File Not Found")
        return ret

    print("Data has been read in...")
    global orig_file 
    orig_file = filepath
    
    curr_line = 0
    index = 0
    index_offset = -4

    for whole_line in data.split("\n"):
        if(whole_line == ''):
            curr_line += 1
            continue

        if ((curr_line % 9) == 0):
            index_offset += 4

        for line in whole_line.split():
            if (index > (len(whole_line.split()) - 1)):
                index = 0

            if((curr_line % 9) == 0):
                ret.append([])
                ret[index + index_offset].append([line])
            else:
                ret[index + index_offset].append([line])

            index += 1

        # done parsing a line
        curr_line += 1

    return ret


## @brief Convert pre-binary bitmap values into binary values
##
## @param mapping, processed input file as a list of list of '.' and 'x' characters
## @return list of bitmap values 
def generate_bitmapping(mapping) -> list:
    """
    ASSIST: Pictorial to assist in understanding movement and processing
    create_list(). Mapping so far is: ret[ ][ ][0][ ]
                                          ^  ^  ^  ^----- selects character
                                          |  |  |
                                          |  |  ------ static
                                          |  ----- row in character list
                                          ----- character #
    """
    ret = []
    binary = 0

    for char in range(len(mapping)):
        ret.append([])
        for col in range(0, len(mapping[0]), 1):
            for row in range(len(mapping[char]) - 1, -1, -1):
                binary <<= 1
                if(mapping[char][row][0][col] == '.'):
                    binary |= 0
                else:
                    binary |= 1
            #print("0b{:08b}".format(binary))
            ret[char].append(["0b{:08b}".format(binary)])
            binary = 0

    return ret 

## @brief Generate the binary bitmap header file
## @param kwargs, dictionary containing necessary variables
def generate_bitmap_file(**kwargs):
    global orig_file
    bitmapping = kwargs["bitmapping"]
    filename = kwargs["filename"]

    header_info = ["/*\n", "* Autogenerated bitmap file from {}\n".format(orig_file), "*/\n\n"] 
    header_info.append("#ifndef _{}_BITMAP_H_\n".format(filename.upper()))
    header_info.append("#define _{}_BITMAP_H_\n\n".format(filename.upper()))

    trailer_info = ["#endif // _{}_BITMAP_H_".format(filename.upper())]

    # compose the body of the file now...
    body_info = ["static const uint8_t {}_bitmap[][8] = \n".format(filename.lower()), "{\n"]
    spacing = 0
    for char_sel in range(len(bitmapping)):
        spacing += 4
        body_info.append("".join(["{}".format(" " * spacing), "{\n"]))
        #body_info.append("{\n".format())
        spacing += 4
        for row_sel in range(len(bitmapping[0])):
            body_info.append("".join(["{}".format(" " * spacing), bitmapping[char_sel][row_sel][0], ",\n"]))
        spacing -= 4
        body_info.append("".join(["{}".format(" " * spacing), "},\n"]))
        spacing -= 4
        body_info.append("\n")
    
    body_info.append("};\n")

    with open("{}/{}_bitmap.h".format(args.destination,filename), "w") as f:
        f.writelines(header_info)
        f.writelines(body_info)
        f.writelines(trailer_info)

    print("{} Header file generated to {}".format(filename, args.destination))

def setup_parser():
    global parser
    parser = argparse.ArgumentParser(
        description=(
        "Script to generate a header file form a bitmap text file.\n\n"
        "Example Usage:\n\n./generate_bit_map_header.py -i /the/path/to/file/<input_filename>.txt -o /<output_fileame>"
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        )
    parser.add_argument('-i','--input', type=str, required=True, help='Full filepath for the input bitmap text file.')
    parser.add_argument('-o','--output', type=str, required=True, help='Full name for the generated output file.')
    parser.add_argument('-dest','--destination', type=str, required=False, default='../include', help='Filepath for where output file will be saved.')
    
if __name__ == "__main__":
    print("Attempting to Execute...")
    
    setup_parser()
    args = parser.parse_args()
 
    map_list = create_list(args.input)
    bit_list = generate_bitmapping(map_list)
    generate_bitmap_file(filename=args.output,bitmapping=bit_list)
